Clean-up

diff --git a/hooks/build b/hooks/build
--- a/hooks/build
+++ b/hooks/build
@@ -5,7 +5,21 @@
 
 # '--push' shorthand for '--output=type=registry'
 
-set -x
+set -ex
+
+# DEP 2/29/24: Pushing to the local registry can fail for PR from a forked repo.
+# The original script I copied does the push to docker hub here, and makes
+# the push script a no-op.  This is not ideal, but harmless with the 'this' tag.
+#
+# Unfortunately, when someone creates a PR from a forked repo, this
+# push fails with a credential issue.  Probably a good idea for
+# security, but also causes the build test to fail.
+#
+# This step pushes to a local registry during build.
+#
+# If anyone wants to change this in the future, be aware during
+# testing.  The old behavior (pushing directly to docker hub) works
+# just fine on a PR from a local branch.
 
 # For this script, set the repo to 127.0.0.1
 OLD_IMAGE_NAME=${IMAGE_NAME}
@@ -19,40 +33,13 @@ echo "Dockerfile Path/Name: ${DOCKERFILE_PATH}"
 BUILDPLATFORM="${BUILDPLATFORM:-"linux/amd64,linux/arm64"}"
 echo "Architectures=${BUILDPLATFORM}"
 
-
 echo "Starting registry"
 
 # Start the local registry
-docker run --net host -d -p 5000:5000 --rm --name registry registry:2
-
-lsof -i -P -n | grep LISTEN
-netstat -tulpn | grep LISTEN
-
-#docker network ls
-#docker network inspect mynet -v
+docker run --net host -d --rm --name registry registry:2
 
 # Build
-# DEP 2/29/24: Pushing to the local registry can fail for PR from a forked repo.
-# The original script I copied does the push to docker hub here, and makes
-# the push script a no-op.  This is not ideal, but harmless with the 'this' tag.
-#
-# Unfortunately, when someone creates a PR from a forked repo, this
-# push fails with a credential issue.  Probably a good idea for
-# security, but also causes the build test to fail.
-#
-# I tried pushing to a repo on localhost, but this also fails for
-# strange reasons (at least as of today).
-#
-# Fortunately, for some reason the build test works if we bounce through a file
-# (awesome.tar).
-#
-# If anyone wants to change this in the future, be aware during
-# testing.  The old behavior (pushing directly to docker hub) works
-# just fine on a PR from a local branch.
 docker buildx build --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --build-arg VCS_REF="$(git rev-parse --short HEAD)" --tag "${IMAGE_NAME}" --platform "${BUILDPLATFORM}" --file "${DOCKERFILE_PATH}" --push .
-
-# Import the image into the local registry
-#docker import awesome.tar ${IMAGE_NAME}
 
 # Tag the local version so that we can push in the push script, should we choose
 docker tag ${IMAGE_NAME} ${OLD_IMAGE_NAME}
